### ISSUE TITLE
Wrong context in folder_contents view

### ISSUE THREAD

**Issue by cekk** [plone/mockup#1016]
Tried with last buildout.coredev.

Steps to reproduce:

- Create some folders structure: /Plone/aaa/bbb/ccc
- Go to portal root -> folder_contents
- navigate through sections until "ccc" folder
- Try to add a new Document

The url will be something like: http://localhost:8080/Plone/aaa/++add++Document

So the context in the sidebar is not updated with the current context. Page title, breadcrumbs and url are correctly set.

**Comment by cekk** [comment]
does anyone can reproduce this bug?

**Comment by mauritsvanrees** [comment]
This issue, or variations thereof, was reported several times. Also, it was claimed to have been fixed several times before, but it seems a beast that raises its head again and again, or in slightly different places.
Anyway, it *should* have been fixed by @fredvd recently, see PR #1028 and #1030, depending on which branch you use. Well, 3.x is for Plone 5.2.
Can you retry on current coredev or on Plone 5.2.3? Both contain his fixes.

**Comment by fredvd** [comment]
There is still one other issue left.  Or actually two.  The drag&drop 'upload' modal also doesn't get updated, so when you navigate a fiw times, and upload something through it, it goes to the wrong folder. 

And 'where smoke there is fire', I noticed that the asterisk for marking the default item in the folder_contents is no longer shown in Plone 5.2.3, It is in Plone 5.2.2 .  But I have no idea yet if one of my fixes introduced this.   https://github.com/plone/Products.CMFPlone/issues/3220

**Comment by fredvd** [comment]
Will be fixed in Plone 5.2.4.  See https://github.com/plone/mockup/pull/1039
