### ISSUE TITLE
Regression in pat-editor?  Escaped source code no longer displayed correctly

### ISSUE THREAD

**Issue by fredvd** [plone/mockup#1265]
There seems to be a regression in the code editor between 6.0.0rc2 and 6.0.0 final. @mauritsvanrees fixed an issue in the editor last week for Easyform.   (https://github.com/collective/collective.easyform/pull/387)  But we had a separate issue in easyform that is also still open and deals with the depends_on and cssclass fields. 

I checked the recent commits, the only relevant one that stand out to me is this one from @thet :  https://github.com/plone/mockup/commit/15576797e51338d4345a90e242ede190d861f6b1

@petschki @frapell Maybe you remember other commits that might cause this regression?

<img width="1692" alt="xmleditor final vs rc2" src="https://user-images.githubusercontent.com/394784/207850635-c333aefa-491a-40cc-a03e-4e8b12d69d26.png">

**Comment by frapell** [comment]
@fredvd Unfortunately no... I'll try to take a look later and report any findings

**Comment by petschki** [comment]
The mockup changes went along with these changes here: https://github.com/plone/plone.app.dexterity/pull/358 ... does the schema model editor work for you? There was a `structure` removed from @thet AFAIK ... maybe that's missing in easyform ...

**Comment by mauritsvanrees** [comment]
I tried the staticresources and dexterity change from Johannes before it was merged, also in combination with easyform, and my conclusion was that it worked:
https://github.com/plone/plone.app.dexterity/pull/358#pullrequestreview-1213203186

Note that in a new PR, Johannes is trying to [simplify the dexterity modeleditor](https://github.com/plone/plone.app.dexterity/pull/359), but that actually makes it a bit closer to how easyform does it. And the two should not really be different anyway.

**Comment by mauritsvanrees** [comment]
Aha, last week I fixed the modeleditor in [dexterity](https://github.com/plone/plone.app.dexterity/pull/356) and in [easyform](https://github.com/collective/collective.easyform/pull/387). With my easyform branch it is now broken again, and this is the branch (or internal release) that Fred is using. But the master branch of easyform still works.

So I fixed the problem in one way, and Johannes has fixed it in a different way. Let's keep his way. I saw he was partially touching code that I just changed a few days before, but since everything seemed to continue to work, it did not raise any warning flags.
