### ISSUE TITLE
translation / i18n confusion

### ISSUE THREAD

**Issue by thet** [plone/mockup#488]
I'm confused about how the mockup translation machinery works.
Mockup tries to get the message catalog in the `widgets` domain via ajax from `plonejs18n`. But - for example - in the german language, there are no translations in plone.app.locales. Still, e.g. the pickadate pattern is translated, because it loads all translations via data-attributes.

I want to fix the translations for the recurrence pattern, but I'm asking myself where to start. Adding it to data-attributes (which can be quite lengthy, look at https://github.com/plone/plone.formwidget.recurrence/blob/master/plone/formwidget/recurrence/browser/i18n.py ), or adding it to the widgets message catalog in plone.app.locales?

Does i18ndude extract message strings from mockup templates?

**Comment by vangheem** [comment]
I think pickadate is different because we're passing in lists of values to the pickadate months, day names, etc into the pickadate widget. We'd have to do a lot of wonky stuff in js or convert the pickadate.js stuff in order to make it use the jsi18n stuff. Look at: https://github.com/plone/plone.app.widgets/blob/master/plone/app/widgets/utils.py#L49 -- it should make sense.

I started trying to add js translations to the recurrence pattern and it was a pain--I gave up. The widgets message catalog is IN plone.app.locales now: https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/widgets.pot

They are generated from mockup using a grunt task. Run make make i18n-dump and then copy the pot file over to plone.app.locales.

**Comment by thet** [comment]
tnx, that should give me a good start

**Comment by thet** [comment]
i'm on Plone 4.3, btw. Maybe I'll just add a widgets catalog to plone.app.widgets and add appropriate stuff to plone.app.locales too, of course

**Comment by pbauer** [comment]
I created a new ``widets.pot`` file with ``make i18n-dump`` and there are many changes (https://github.com/collective/plone.app.locales/commit/efedb6d2). Then I synced the po-files and created a pr with all that: https://github.com/collective/plone.app.locales/pull/54

Now I'd start translating strings. Is that ok?

**Comment by vangheem** [comment]
That'd be great!

**Comment by vincentfretin** [comment]
Five years later :-)
Remaining internationalization issues in folder contents: https://github.com/plone/Products.CMFPlone/issues/2188#issuecomment-646535054
Documentation how to test changes in Plone and handle translations: https://github.com/plone/mockup/pull/985

**Comment by vincentfretin** [comment]
There exists an issue for each i18n bugs I think now. I'm closing this issue.
