### ISSUE TITLE
toggle pattern error?

### ISSUE THREAD

**Issue by gforcada** [plone/mockup#489]
I see that [travis is green](https://travis-ci.org/plone/mockup/jobs/60929422) but looking closer at the console output I see:

```
ERROR: 'patterns.pat.toggle:', 'Failed while initializing "toggle" pattern.'
'patterns.pat.toggle:', 'Failed while initializing "toggle" pattern.'
PhantomJS 1.9.8 (Linux): Executed 140 of 240 (skipped 1) SUCCESS (0 secs / 1.11 secs)
ERROR LOG: 'patterns.pat.toggle:', 'Failed while initializing "toggle" pattern.'
ERROR: 'patterns.pat.toggle:', Error{message: 'No target found for "#notarget".', line: 247, sourceId: 47794208048576, sourceURL: 'http://localhost:9876/base/bower_components/jquery/dist/jquery.js?73e5d044bd153dd912930e8be433059454ce19cd', stack: 'Error: No target found for "#notarget".
```

That's at line 1301 at the link provided before.

Then the tests end with ``Executed 238 of 240 (skipped 2)``. These 2 skipped are the ones from the toggle pattern.

I'm mostly creating this issue so that someone can shed some light on it, or give it attention to someone with better judgment over it :)

**Comment by vangheem** [comment]
There is nothing skipped from the toggle pattern. Skipped is not from an error. An error will show explicitly and cause a failure. Skipping is caused by specifying `it.skip('my test'` for a test to actually skip the result of a test. It's explicitly done on 2 tests right now.

As for the toggle error, it's console output from this test: https://github.com/plone/mockup/blob/master/mockup/tests/pattern-toggle-test.js#L277 and it is expected--just ignore.
