### ISSUE TITLE
draging images fails in IE 10 (update to tinymce 4.2.5)

### ISSUE THREAD

**Issue by domruf** [plone/mockup#569]
When you try to drag an image to another part of the text
instead of moving the image a second image is created at the beginning of the text.

Updating tinymce to 4.2.5 solved to problem.

**Comment by domruf** [comment]
http://www.tinymce.com/develop/bugtracker_view.php?id=7598

**Comment by vangheem** [comment]
We deploy with bower and https://github.com/artursmirnov/tinymce_builded . They have no updated so I made a ticket: https://github.com/artursmirnov/tinymce_builded/issues/4

**Comment by domruf** [comment]
May I ask why you are not using https://github.com/tinymce/tinymce directly?

**Comment by vangheem** [comment]
We could go back and look at it. We had problems with the way it was packaged. It couldn't be built properly.

**Comment by domruf** [comment]
Well, I simple replaced "tinymce-builded": "4.1.9" with "tinymce": "4.2.5" in bower.json,
changed the paths in config.js and 
removed the dependency to compat3x and the basics seem to work.
But of course I don't know the details.

**Comment by vangheem** [comment]
Can you make a PR with it so we can take a look? Maybe we can update.

**Comment by frapell** [comment]
A while ago I think I pulled from tinymce instead of tinymce-builded and it worked fine... never asked why we were pulling from -builded.

Will try to send a PR with the change if it works fine

**Comment by frapell** [comment]
I have failed at the moment to switch this to the official build, and for today I cannot put more time into this.

For what I've seen, there are some missing stuff from the official build, such as the compat3x plugin (not sure if we actually need it), also the lang files, and some .less are either missing or renamed (The ones used in mockup/patterns/tinymce/less/pattern.tinymce.less)

Also, https://github.com/plone/mockup-core/blob/master/js/grunt.js needs to be fixed to point to the different folder (actually, shouldn't this be moved to mockup instead of mockup-core?)

**Comment by vangheem** [comment]
See https://github.com/plone/Products.CMFPlone/pull/919

Thoughts?
