### ISSUE TITLE
relatedItems broken with lineage installed

### ISSUE THREAD

**Issue by petschki** [plone/mockup#591]
This is only if you're editing a lineage subsite behind a VHM mapped nginx vhost. so if your domain root is for eg `/Plone/subsite` and you want to browse your folder structure within the relatedItems pattern (tinymce internal links, images, or related items etc..) , you only see the root level items but nothing from subfolders like `/Plone/subsite/downloads` ... 

this is because the `path`criteria for the vocabulary query includes the subsite id `/subsite/downloads` which gets parsed to `/Plone/subsite/subsite/downloads` for the catalog which obviously returns an empty result.

I don't know exactly where, but if someone can give me a hint, i'll fix this @thet @vangheem ?

**Comment by petschki** [comment]
Fixed https://github.com/plone/plone.app.content/pull/56 and https://github.com/plone/plone.app.widgets/pull/113

**Comment by thet** [comment]
Great! Strange, I didn't run into this problem myself - I'm using lineage and plone.app.widgets also for one project. I guess, it's because of ``collective.rooter``, which roots all catalog queryies without an explicit path set to the navigation root ( https://github.com/collective/collective.rooter/blob/master/collective/rooter/catalog.py#L10 ).

Maybe because of collective.rooter, which roots all
