### ISSUE TITLE
Use namespaced requirejs

### ISSUE THREAD

**Issue by vangheem** [plone/mockup#626]
Poking around some odoo code, I noticed they do this: https://github.com/odoo/odoo/blob/52484b0132ee3e0063dd67cc3c2eb434f99f5db8/addons/pos_restaurant/static/src/js/multiprint.js#L1

This would get around issues with addons having special non-compatible requirejs code.

Is it worth converting our stuff to this?

\cc @bloodbare @thet @frapell @ebrehault  anyone else have opinions?

**Comment by frapell** [comment]
@vangheem Sorry, I'm not very familiar with these advanced usages of requirejs. If you point me to some documentation in the matter I can read, then I might be able to help...

**Comment by vangheem** [comment]
It's just so we don't have a global require and define floating around...

**Comment by thet** [comment]
I'm rephrasing this, because this RequireJS confuses me each time.

That will help with this "mismatched anonymous define error", true? http://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#usage-of-define-and-require-and-the-mismatched-anonymous-define-error
When no define is available, libraries cannot register themselves, like here: https://github.com/Leaflet/Leaflet/blob/v0.7.7/src/Leaflet.js#L13
Still, if we need these libs managed by RequireJS, we do add them to the RequireJS path configuration.

Well, I think the approach of namespacing the ``define`` and ``require`` globals would help. Although - is there any benefit, since you've already done the unloading of ``require`` and ``define`` before loading legacy scripts?

**Comment by vangheem** [comment]
Right. I'm not sure it'd actually work though as it requires everything to buy into it. So, for instance, patternslib wouldn't work with it.

Ignore I guess. Just thought it was interesting...

**Comment by thet** [comment]
Uh, patternslib... That's a showstopper for this feature.
Their approach is definetly interesting, though!
