### ISSUE TITLE
select2 widget broken behavior with amp&;

### ISSUE THREAD

**Issue by tiberiuichim** [plone/mockup#706]
A lot of problems when an editor inserts a tag with an ampersand:
- not possible to delete this tag with the ampersand
- the tags are split wrong
  etc

I've tracked the problem to this line in /mockup/patterns/select2/pattern.js

```
data.push({id: utils.escapeHTML(this), text: utils.escapeHTML(text)});
```

If the escapeHTML call is not used at all, things work just fine.

**Comment by jensens** [comment]
i can confirm this.

**Comment by petschki** [comment]
jep here too ... for example if you want to add a keyword "Q&A" it get's splitted by ";" in `["Q&amp", "A"]` values. Completely removing this would lead to XSS vulnerability. I'd suggest to introduce a more restrictive utils method:

```
  var removeHTML = function(val) {
    return val.replace(/<[^>]+>/ig, "");
  };
```
and implement it instead of `utils.escapeHTML` in `pat-select2`

ping @thet @vangheem any thoughts ?

**Comment by thet** [comment]
Fixed with: https://github.com/plone/mockup/issues/706
