### ISSUE TITLE
lazy loading of moment.js locales not reliable

### ISSUE THREAD

**Issue by agitator** [plone/mockup#925]
Following up on https://github.com/plone/plone.staticresources/pull/46

Can't exactly pin point since when but the issue came up with an upgrade to Plone 5.2 with Py3.

If I create a new site in german, documentByLine says ... zuletzt geändert: 4 minutes ago
When I turn on/off development mode in the resource registry, it seems to work sometimes.
If I add multilingual and more languages, the moment locales load most of the time, but don't seem to be active or really localize the date.

Creating a specific moment bundle was only done to advance on more flexible resource loading or even disable it at all. Imho didn't have any impact...

Also stumbled over https://stackoverflow.com/questions/52899694/moment-js-loads-localization-too-late-when-lazy-loaded

**Comment by davilima6** [comment]
Thanks for the pointers! I'll try to reproduce as soon as possible and update here.

**Comment by davilima6** [comment]
I confirm I could reproduce the issue and add that even without changing any settings (e.g. resource registries) the behaviour is intermittent. Besides when I throttle my connection to Fast 3G (Chrome) I invariably get the correct results so it does look like a race condition.

Looking at code it seems we need to wait the require instruction to download and complete load the locale module before setting the moment locale:

* This is what we need to wait: https://github.com/plone/mockup/blob/273452383863e6aab3047c2bda12659b9d2f566e/mockup/patterns/moment/pattern.js#L125
* Before running this: https://github.com/plone/mockup/blob/273452383863e6aab3047c2bda12659b9d2f566e/mockup/patterns/moment/pattern.js#L151

The thing is AFAIK Require.js does not handle Promises or async functions natively which would be needed as an argument to `define` in order to use [await before the lazyLoadMomentLocale() call](https://github.com/plone/mockup/blob/273452383863e6aab3047c2bda12659b9d2f566e/mockup/patterns/moment/pattern.js#L88):
* https://github.com/requirejs/requirejs/issues/1446
* https://stackoverflow.com/questions/54424914/javascript-requirejs-with-async-await

I'll check but if you have experience with this please share.

**Comment by vincentfretin** [comment]
Ha ha ha. I didn't see this issue here. There was another issue by @dbitouze the 2 Oct 2019 https://github.com/plone/Products.CMFPlone/issues/2953 
If fixed the issue in PR https://github.com/plone/mockup/pull/987 and the new bundles are in https://github.com/plone/plone.staticresources/pull/87 ready for Plone 5.2.2.
